//
// CreatedAsyncTask.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Created Asynchronous task with service */

public struct CreatedAsyncTask: Codable {

    public enum Status: String, Codable { 
        case malformed = "MALFORMED"
        case unexpected = "UNEXPECTED"
        case success = "SUCCESS"
        case queued = "QUEUED"
        case accessDenied = "ACCESS_DENIED"
    }
    public var timestamp: Int?
    public var status: Status?
    public var taskId: String

    public init(timestamp: Int?, status: Status?, taskId: String) {
        self.timestamp = timestamp
        self.status = status
        self.taskId = taskId
    }

    public enum CodingKeys: String, CodingKey { 
        case timestamp
        case status
        case taskId = "task_id"
    }

}

