//
// HealthReport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Health Report Report */

public struct HealthReport: Codable {

    public enum TestType: String, Codable { 
        case positive = "positive"
        case negative = "negative"
    }
    public var timestamp: Int?
    public var numSymptoms: Int?
    public var proximity: Bool?
    public var testType: TestType?
    public var commercialFlight: Bool?

    public init(timestamp: Int?, numSymptoms: Int?, proximity: Bool?, testType: TestType?, commercialFlight: Bool?) {
        self.timestamp = timestamp
        self.numSymptoms = numSymptoms
        self.proximity = proximity
        self.testType = testType
        self.commercialFlight = commercialFlight
    }

    public enum CodingKeys: String, CodingKey { 
        case timestamp
        case numSymptoms = "num_symptoms"
        case proximity
        case testType = "test_type"
        case commercialFlight = "commercial_flight"
    }

}

