//
// IdentifiedUserEntryItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Status of whether or not a user is permitted to enter the school */

public struct IdentifiedUserEntryItem: Codable {

    public enum Reason: String, Codable { 
        case health = "health"
        case location = "location"
    }
    public var name: String?
    public var entry: Bool
    public var reason: Reason
    public var health: UserHealthItem?
    public var location: UserLocationItem?

    public init(name: String?, entry: Bool, reason: Reason, health: UserHealthItem?, location: UserLocationItem?) {
        self.name = name
        self.entry = entry
        self.reason = reason
        self.health = health
        self.location = location
    }


}

