//
// InteractionReport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Interaction report schema for API validation and documentation */

public struct InteractionReport: Codable {

    public var targets: [String]

    public init(targets: [String]) {
        self.targets = targets
    }


}

