//
// ListUsersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Listing users in the database response */

public struct ListUsersResponse: Codable {

    public enum Status: String, Codable { 
        case malformed = "MALFORMED"
        case unexpected = "UNEXPECTED"
        case success = "SUCCESS"
        case queued = "QUEUED"
        case accessDenied = "ACCESS_DENIED"
    }
    public var timestamp: Int?
    public var status: Status?
    public var users: [User]

    public init(timestamp: Int?, status: Status?, users: [User]) {
        self.timestamp = timestamp
        self.status = status
        self.users = users
    }


}

