//
// SymptomReport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Symptom Report */

public struct SymptomReport: Codable {

    public var timestamp: Int?
    public var numSymptoms: Int?

    public init(timestamp: Int?, numSymptoms: Int?) {
        self.timestamp = timestamp
        self.numSymptoms = numSymptoms
    }

    public enum CodingKeys: String, CodingKey { 
        case timestamp
        case numSymptoms = "num_symptoms"
    }

}

