//
// TestReport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Report either a positive or negative test */

public struct TestReport: Codable {

    public enum TestType: String, Codable { 
        case positive = "positive"
        case negative = "negative"
    }
    public var testType: TestType

    public init(testType: TestType) {
        self.testType = testType
    }

    public enum CodingKeys: String, CodingKey { 
        case testType = "test_type"
    }

}

