//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** User Schema for API validation and documentation */

public struct User: Codable {

    public enum SignupAt: String, Codable { 
        case inactive = "inactive"
        case active = "active"
    }
    public var firstName: String
    public var lastName: String
    public var email: String
    public var school: String
    public var signupAt: SignupAt?

    public init(firstName: String, lastName: String, email: String, school: String, signupAt: SignupAt?) {
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.school = school
        self.signupAt = signupAt
    }

    public enum CodingKeys: String, CodingKey { 
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case school
        case signupAt = "signup_at"
    }

}

