//
// UserLocationItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Entity representing user location */

public struct UserLocationItem: Codable {

    public enum Color: String, Codable { 
        case danger = "danger"
        case yellow = "yellow"
        case gray = "gray"
        case success = "success"
    }
    public enum Location: String, Codable { 
        case campus = "campus"
        case remote = "remote"
        case quarantined = "quarantined"
    }
    public var color: Color?
    public var location: Location?

    public init(color: Color?, location: Location?) {
        self.color = color
        self.location = location
    }


}

