//
// UserRiskItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Entity representing user risk */

public struct UserRiskItem: Codable {

    public var email: String?
    public var timestamp: String?
    public var color: String?
    public var criteria: [String]?

    public init(email: String?, timestamp: String?, color: String?, criteria: [String]?) {
        self.email = email
        self.timestamp = timestamp
        self.color = color
        self.criteria = criteria
    }


}

