//
// SyncAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SyncAPI {
    /**
     List Users

     - parameter authorization: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listUsers(authorization: String, completion: @escaping ((_ data: ListUsersResponse?,_ error: Error?) -> Void)) {
        listUsersWithRequestBuilder(authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List Users
     - GET /list/users

     - examples: [{contentType=application/json, example={
  "users" : [ {
    "school" : "school",
    "last_name" : "last_name",
    "first_name" : "first_name",
    "email" : "email"
  }, {
    "school" : "school",
    "last_name" : "last_name",
    "first_name" : "first_name",
    "email" : "email"
  } ],
  "timestamp" : 0,
  "status" : "SUCCESS"
}}]
     - parameter authorization: (header)  

     - returns: RequestBuilder<ListUsersResponse> 
     */
    open class func listUsersWithRequestBuilder(authorization: String) -> RequestBuilder<ListUsersResponse> {
        let path = "/list/users"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ListUsersResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     Entry Card

     - parameter authorization: (header)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userStatus(authorization: String, completion: @escaping ((_ data: IdentifiedUserEntryItem?,_ error: Error?) -> Void)) {
        userStatusWithRequestBuilder(authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Entry Card
     - GET /get-user-entry

     - examples: [{contentType=application/json, example={
  "entry" : true,
  "reason" : "health",
  "name" : "name",
  "health" : {
    "color" : "danger",
    "criteria" : [ "criteria", "criteria" ]
  },
  "location" : {
    "color" : "danger",
    "location" : "campus"
  }
}}]
     - parameter authorization: (header)  

     - returns: RequestBuilder<IdentifiedUserEntryItem> 
     */
    open class func userStatusWithRequestBuilder(authorization: String) -> RequestBuilder<IdentifiedUserEntryItem> {
        let path = "/get-user-entry"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<IdentifiedUserEntryItem>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
